version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    env_file:
      - .env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
